Repository Abraarkhan/Java_Algorithms, pull requests merged in 2021-10, with the labels that each got.

#51 first and last digit
  automorphic.java
  convtocap.java
  fdld.java
Labels: hacktoberfest-accepted, approved

#52 Construct a stack using arrays
  README.md
  stackArrayApp.java
Labels: hacktoberfest-accepted, approved

#53 Create BinarySearchIterative.java
  BinaryExponentiation.java
  BinarySearchIterative.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2021

#56 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, approved

#55 Create SieveOfEratosthenes.java
  SieveOfEratosthenes.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2021

#54 Java program to illustrate creating an array of integers, puts some values in the array, and prints each value to standard output.
  Accessing_Java_Array_Elements_using_for_Loop.java
Labels: hacktoberfest-accepted, approved

#57 find happy number
  happy.java
Labels: hacktoberfest-accepted, approved

#59 Create ModularExp.java
  ModularExp.java
Labels: hacktoberfest-accepted, approved

#58 shorting
  BubbleShortDemo.java
  QuickSortDemo.java
  insertionshortdemo.java
  mergeshortdemo.java
  package-info.java
  selectionshort.java
  shellshort.java
Labels: hacktoberfest-accepted, approved

#61 Java implementation of graph
  Implementing_graph.java
Labels: hacktoberfest-accepted, approved

#64 Color Fill in Java
  Color_fill.java
Labels: hacktoberfest-accepted, approved

#62 HashTable Algorithm
  HashTableTest.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2021

#65 Sum Untill The User Enters Zero In Java
  SumUntilEntersZero.java
Labels: hacktoberfest-accepted, approved

#66 Calculator.java is a simple calculator made using java swing
  Calculator.java
Labels: hacktoberfest-accepted, approved
