Repository Abraarkhan/Java_Algorithms, pull requests merged in 2022-10, with the labels that each got.

#67 ArraysSort with Java util class
  sort.java
Labels: hacktoberfest-accepted, approved

#70 Readme updates
  DSA_JAVA/readme.md
Labels: documentation, hacktoberfest-accepted, approved, hacktoberfest2022

#69 Minimum Spanning Tree – MST using Kruskal’s Algo
  KruskalsAlgo.java
Labels: enhancement, hacktoberfest-accepted, approved, hacktoberfest2022

#75 Half Pyramid
  Half Pyramid
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#78 Enhancement of Readme
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, approved, hacktoberfest2022

#80 Merge without extra space
  mergeWithoutExtraSpace.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#79 Pair Sum In Sorted Array
  pairSumInSortedArray.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#81 Two Sum
  TwoSum.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#86 Create Voice_asistant.java
  Voice_asistant.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#85 Create Reverse K Group.java
  Reverse K Group.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#84 Create Merge k Sorted Lists.java
  Merge k Sorted Lists.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#82 Subset Finder Algorithm
  subsets.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#87 Create Valid_parentheses.java
  Valid_parentheses.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#89 Create Valid Sudoku.java
  Valid Sudoku.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#92 readme
  Password Generator/readme.md
Labels: documentation, hacktoberfest-accepted, approved, hacktoberfest2022

#94 Create p_c.java
  p_c.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#91 Dependencies Files
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Core.1.0.0/Microsoft.AspNet.Identity.Core.1.0.0.nupkg
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Core.1.0.0/Microsoft.AspNet.Identity.Core.1.0.0.nuspec
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Core.1.0.0/lib/net45/Microsoft.AspNet.Identity.Core.dll
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Core.1.0.0/lib/net45/Microsoft.AspNet.Identity.Core.xml
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.EntityFramework.1.0.0/Microsoft.AspNet.Identity.EntityFramework.1.0.0.nupkg
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.EntityFramework.1.0.0/Microsoft.AspNet.Identity.EntityFramework.1.0.0.nuspec
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.EntityFramework.1.0.0/lib/net45/Microsoft.AspNet.Identity.EntityFramework.dll
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.EntityFramework.1.0.0/lib/net45/Microsoft.AspNet.Identity.EntityFramework.xml
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Owin.1.0.0/Microsoft.AspNet.Identity.Owin.1.0.0.nupkg
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Owin.1.0.0/Microsoft.AspNet.Identity.Owin.1.0.0.nuspec
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Owin.1.0.0/lib/net45/Microsoft.AspNet.Identity.Owin.dll
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Identity.Owin.1.0.0/lib/net45/Microsoft.AspNet.Identity.Owin.xml
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Mvc.5.0.0/Microsoft.AspNet.Mvc.5.0.0.nupkg
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Mvc.5.0.0/Microsoft.AspNet.Mvc.5.0.0.nuspec
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Mvc.5.0.0/lib/net45/System.Web.Mvc.dll
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Mvc.5.0.0/lib/net45/System.Web.Mvc.xml
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Razor.3.0.0/Microsoft.AspNet.Razor.3.0.0.nupkg
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Razor.3.0.0/Microsoft.AspNet.Razor.3.0.0.nuspec
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Razor.3.0.0/lib/net45/System.Web.Razor.dll
  DSA_JAVA/Online-Survey-System/Packages/Microsoft.AspNet.Razor.3.0.0/lib/net45/System.Web.Razor.xml
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Content/Scripts/jquery-1.10.2-vsdoc.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Content/Scripts/jquery-1.10.2.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Content/Scripts/jquery-1.10.2.min.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Content/Scripts/jquery-1.10.2.min.map
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Tools/common.ps1
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Tools/install.ps1
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Tools/jquery-1.10.2.intellisense.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/Tools/uninstall.ps1
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/jQuery.1.10.2.nupkg
  DSA_JAVA/Online-Survey-System/Packages/jQuery.1.10.2/jQuery.1.10.2.nuspec
  DSA_JAVA/Online-Survey-System/Packages/jQuery.Validation.1.11.1/Content/Scripts/jquery.validate-vsdoc.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.Validation.1.11.1/Content/Scripts/jquery.validate.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.Validation.1.11.1/Content/Scripts/jquery.validate.min.js
  DSA_JAVA/Online-Survey-System/Packages/jQuery.Validation.1.11.1/jQuery.Validation.1.11.1.nupkg
  DSA_JAVA/Online-Survey-System/Packages/jQuery.Validation.1.11.1/jQuery.Validation.1.11.1.nuspec
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#95 Readme update Hacktoberfest
  DSA_JAVA/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted, approved, hacktoberfest2022

#98 created binary_tree.java
  binary_tree.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#97 Readme.md update
  README.md
  alphabet.java
  p_c.java
  pattern.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#100 Added Isomorphic.java
  Isomorphic.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#99 Added Disjoint Set Union template for Java
  DisjointSetUnion.java
  README.md
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#109 Check Alphabet
  alphaornum.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#108 Display Fibonacci Series
  fibo.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#107 Multiplication Table
  table.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#106 Check if a Number is Positive or Negative
  posneg.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#105 Sum of Natural Numbers
  sum.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#104 Factorial of a number
  factorial.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#103 Check a Leap Year
  leapyear.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#102 Check Prime Number
  primeNumber.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#101 Function to calculate factors of a number
  Factors.java
  README.md
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#110 Currency Converter
  Currency Converter
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#111 sql_database
  sql_database.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#112 transpose of a matrix
  transpose.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#113 Configs files in online-survey-system
  DSA_JAVA/Online-Survey-System/App_Start/BundleConfig.cs
  DSA_JAVA/Online-Survey-System/App_Start/FilterConfig.cs
  DSA_JAVA/Online-Survey-System/App_Start/RouteConfig.cs
  DSA_JAVA/Online-Survey-System/App_Start/Startup.Auth.cs
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#114 frontend development
  DSA_JAVA/Online-Survey-System/Content/Site.css
  DSA_JAVA/Online-Survey-System/Content/bootstrap.css
  DSA_JAVA/Online-Survey-System/Content/bootstrap.min.css
  DSA_JAVA/Online-Survey-System/Controllers/AccountController.cs
  DSA_JAVA/Online-Survey-System/Controllers/HomeController.cs
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#115 fonts choices
  DSA_JAVA/Online-Survey-System/fonts/glyphicons-halflings-regular.eot
  DSA_JAVA/Online-Survey-System/fonts/glyphicons-halflings-regular.svg
  DSA_JAVA/Online-Survey-System/fonts/glyphicons-halflings-regular.ttf
  DSA_JAVA/Online-Survey-System/fonts/glyphicons-halflings-regular.woff
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#116 Number Guessing Game
  Number Guessing Game
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#118 Included the models and icons
  DSA_JAVA/Online-Survey-System/Models/AccountViewModels.cs
  DSA_JAVA/Online-Survey-System/Models/IdentityModels.cs
  DSA_JAVA/Online-Survey-System/favicon.ico
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#117 hashmap example
  bst.java
  hashmap.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#119 front end, web view
  DSA_JAVA/Online-Survey-System/Views/Account/ExternalLoginConfirmation.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/ExternalLoginFailure.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/Login.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/Manage.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/Register.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/_ChangePasswordPartial.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/_ExternalLoginsListPartial.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/_RemoveAccountPartial.cshtml
  DSA_JAVA/Online-Survey-System/Views/Account/_SetPasswordPartial.cshtml
  DSA_JAVA/Online-Survey-System/Views/Home/About.cshtml
  DSA_JAVA/Online-Survey-System/Views/Home/Contact.cshtml
  DSA_JAVA/Online-Survey-System/Views/Home/Index.cshtml
  DSA_JAVA/Online-Survey-System/Views/Shared/Error.cshtml
  DSA_JAVA/Online-Survey-System/Views/Shared/_Layout.cshtml
  DSA_JAVA/Online-Survey-System/Views/Shared/_LoginPartial.cshtml
  DSA_JAVA/Online-Survey-System/Views/Web.config
  DSA_JAVA/Online-Survey-System/Views/_ViewStart.cshtml
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#122 insertMId
  insertmid.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#123 search ele _dl
  search ele _dl
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#124 Binary_Tree
  Binary_Tree
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#125 Bubble_sort
  Bubble_sort
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#126 Sqrt(x) - Using Java
  majorityelement.java
  sqrt.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#127 Contains Duplicate - Using Java
  containsduplicate.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#128 Group Anagrams - Using Java
  groupanagrams.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022

#129 Next Permutation - Using Java
  nextpermutation.java
Labels: hacktoberfest-accepted, approved, hacktoberfest2022
